controller_manager:
  ros__parameters:
    update_rate: 200
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    servo_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    servo_position_controller:
      type: position_controllers/JointGroupPositionController

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

servo_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - F_L_0
      - F_L_1
      - F_L_2
      - F_R_3
      - F_R_4
      - F_R_5
      - B_L_6
      - B_L_7
      - B_L_8
      - B_R_9
      - B_R_10
      - B_R_11
    command_interfaces:
      - position
    state_interfaces:
      - position
    open_loop_control: true
    allow_integration_in_goal_trajectories: true

servo_position_controller:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints:
      - F_L_0
      - F_L_1
      - F_L_2
      - F_R_3
      - F_R_4
      - F_R_5
      - B_L_6
      - B_L_7
      - B_L_8
      - B_R_9
      - B_R_10
      - B_R_11
    command_interfaces:
      - position
    state_interfaces:
      - position